WIP: ConsoleBase: move pexpect dependency to a separate class
Witekio/pluma-automation pull request #116
Opened 2020-10-01 17:44 UTC by Pixep

Separate entirely pexpect from ConsoleBase, to reduce the scope of this dependency. Will also allow much more flexible testing, and future extension of the code.

2020-10-02 12:09 UTC, mjftw reviewed
Seems like a good idea to split. Nice work picking this all apart! 
Will have to make sure we do extensive testing to check that everything still works.
Ideally I'd like for the interfaces for the top level console controller classes (E.g. `SerialConsole`, `HostConsole`) to not have to change so that no callers need know that the internals have had a big refactor.

2020-10-02 12:09 UTC, mjftw commented on pluma/core/baseclasses/consoleinteractor.py
> +    def _on_opened(self):
Do we need an extra `_on_opened()` method? Could this be part of `open()`?
I guess I don't fully understand the use case for this method.

2020-10-05 01:09 UTC, Pixep commented on pluma/core/baseclasses/consoleinteractor.py
> +    def read_buffer(self) -> str:
(outdated but property is still there) I believe this should be a property, as there is no side effect. The `read_` prefix is annoying though, I agree. Maybe `reception_buffer` instead?

2020-10-05 11:14 UTC, mjftw requested changes
I think definitely this is a change for the better.
Added a few comments about possible change ideas, open to discussion on all of them of course.

2020-10-05 11:14 UTC, mjftw commented on pluma/core/baseclasses/consoleinteractor.py
> +        '''Wait a maximum duration of 'timeout' for a matching regex'''
On all of these abstract methods we'll want to be really explicit about what each of the arguments and return values should do. Especially so with the return tuple, since if the implementing function gets this wrong we'll have some strange errors.

To make this more explicit, I might recommend using a [namedtuple](https://docs.python.org/3/library/collections.html#collections.namedtuple) instead, explicitly specifying each of the tuple value's intent.

```python

MatchResults = namedtuple('MatchResults', ('regex_match', 'text_match', 'received'))
...
...
    @abstractmethod
    def wait_for_match(self, match: List[str], timeout: int = None) \
            -> MatchResults:
        '''Wait a maximum duration of 'timeout' for a matching regex'''
```

You can still use tuple unpacking with this so none of the callers would have to care, but we'd get clear intent for implementing classes, and better type checking.

```python
>>> MatchResults = namedtuple('MatchResults', ('regex_matched', 'text_matched', 'received'))

>>> def foo() -> MatchResults:
...    return MatchResults('a', 'b', 'c')

>>> x, y, z = foo()

>>> print(x, y, z)
a b c
```

2020-10-05 11:14 UTC, mjftw commented on tests/generic/generic/test_ConsoleBase.py
> +class TestConsole(ConsoleBase):
Not really important, but I might call this `MockConsole` to make it really clear what it does.
Although we do have a [ConsoleMock](https://github.com/Witekio/pluma-automation/blob/master/pluma/core/mocks/consolemock.py) class already, but I think really that there shouldn't be mock classes in `pluma/core/mocks` at all.

2020-10-06 20:10 UTC, Pixep commented on pluma/core/baseclasses/consoleinteractor.py
> +    def read_buffer(self) -> str:
Renamed to `reception_buffer`

2020-10-06 20:13 UTC, Pixep commented on pluma/core/baseclasses/consolebase.py
> +        '''Return wether the console is opened or not'''
Fixed

2020-10-06 20:16 UTC, Pixep commented on pluma/core/baseclasses/consoleinteractor.py
> +        if (not console_cmd and not console_fd) or (
Changed to `is None` for both, for symmetry, and this made more sense overall

2020-10-06 20:23 UTC, Pixep commented on pluma/core/baseclasses/consoleinteractor.py
> +    @abstractmethod
Yes that was exactly my train of thought, requiring a strategy pattern, or other implementations. And I think for now this would add too much complexity for no real value. This set of 2 methods is a sign that something else might be needed, but sometimes its also better to be lazy about it, especially as, right now, there is only a single PexpectInteractor/Engine.

I see a future change there, when needed, as this is already encapsulated in the new "ConsoleEngine" class, I don't think we have the luxury to "wait and see" what decision makes more sense

2020-10-06 20:24 UTC, Pixep commented on pluma/core/baseclasses/consoleinteractor.py
> +        '''Wait a maximum duration of 'timeout' for a matching regex'''
Yeah I wanted to have that, I definitely struggled with the older original methods at first to know what this was all about. Will add.

2020-10-06 21:21 UTC, Pixep commented
@mjftw : FileExists and friends unit tests are failing, thought they are working when I try using them manually. The log shows the error (FAIL file does not exist), but the unit test doesn't catch it, and worse, the summary status (PASS/FAIL) is (=All tests succeeded), though some tests failed... couldn't understand the problem yet.

2020-10-06 21:46 UTC, Pixep commented on tests/generic/generic/test_ConsoleBase.py
> +class TestConsole(ConsoleBase):
Removed it for now, this shouldn't even be here yet

2020-10-06 22:20 UTC, Pixep commented on pluma/core/baseclasses/consoleinteractor.py
> +        '''Wait a maximum duration of 'timeout' for a matching regex'''
Done

2020-10-07 11:42 UTC, mjftw commented
> @mjftw : FileExists and friends unit tests are failing, thought they are working when I try using them manually. The log shows the error (FAIL file does not exist), but the unit test doesn't catch it, and worse, the summary status (PASS/FAIL) is (=All tests succeeded), though some tests failed... couldn't understand the problem yet.
> EDIT: nvm, fixed!

Ooo err nasty, what was causing it?

2020-10-07 13:15 UTC, mjftw approved these changes
This is looking great!
Only a couple of very minor comments, but nothing worth blocking merging over, so approved.
We'll want to merge this one before https://github.com/Witekio/pluma-automation/pull/132 as that'll save some conflicts in the `pluma/core/mocks` classes.

2020-10-07 18:39 UTC, Pixep commented on pluma/core/baseclasses/consoleengine.py
> +@dataclass
Yeah I like the dataclass better to make data, type explicit, and completion. But that might come down to preference. Added the frozen attribute.

2020-10-07 18:41 UTC, Pixep commented on pluma/core/baseclasses/consoleengine.py
> +        '''Open a specific file description as the console'''
Yep, typo. Done.

2020-10-08 03:36 UTC, Pixep commented
Fixed some unit test weirdness, and improved the coverage a bit

2020-10-08 11:28 UTC, mjftw commented on pluma/core/baseclasses/consoleengine.py
> +@dataclass
> Yeah I like the dataclass better to make data, type explicit, and completion. But that might come down to preference. Added the frozen attribute.

Oh yeah don't get me wrong, I think dataclasses are great, and a definite step up over named tuples.
I just like immutability wherever possible. Immutable dataclasses are the best of all worlds.

2020-10-08 11:50 UTC, mjftw approved these changes
Very pleased so say that I have no points for improvement, so hitting approve 👍🏼
Thanks for all your work on this one, it's a much better architecture now!

2020-10-08 11:50 UTC, merged