Feature/targetconfig warn on shadowed variables
Witekio/pluma-automation pull request #119
Opened 2020-10-05 12:28 UTC by mjftw

I added an extra commit to cut down some shorten some unit tests near the one I added too.
Not related, but may as well while I'm there.

2020-10-06 16:50 UTC, Pixep commented on pluma/cli/api.py
> +                        f'{os.linesep}Using environment: {env_value}')
Nit:
* defined in _both_ ...
* {os.linesep}    Using environment:
    * Using 4 spaces indentation here, as for other similar messages

2020-10-06 16:50 UTC, Pixep commented on tests/generic/cli/test_Pluma.py
> +    monkeypatch.setenv('abc', 'def')
Much cleaner!

2020-10-06 17:06 UTC, Pixep requested changes
Minor change regarding the output

2020-10-07 13:23 UTC, mjftw commented on pluma/cli/api.py
> +                        f'{os.linesep}Using environment: {env_value}')
I think I understood what you mean and have fixed, but let me know if I've misunderstood.

2020-10-08 03:41 UTC, Pixep commented on pluma/cli/api.py
> +                        f'{os.linesep}Using environment: {env_value}')
I meant
> "{variable}" defined in 
to
> "{variable}" defined in **both**

and what we probably need 4 spaces before `Using environment:` if we want to match how similar messages are displayed :)

2020-10-08 03:42 UTC, Pixep approved these changes
Added that one comment, otherwise g2g

2020-10-08 10:18 UTC, mjftw commented on pluma/cli/api.py
> +                        f'{os.linesep}Using environment: {env_value}')
I think that's what I've done

2020-10-08 10:18 UTC, merged