testconfig: added test descriptions to 'tests' printout
Witekio/pluma-automation pull request #137
Opened 2020-10-08 05:21 UTC by Zematus

Adds test-level descriptions for #96. Later will add parameter info for test-specific queries

2020-10-08 12:02 UTC, mjftw commented
For reference, this is the new console output with this PR:
```
(venv) merlin@pangolin:~/projects/pluma-automation$ pluma tests -c pluma.yml.sample -t pluma-target.yml.sample 

Device actions:
    [x] set
          {"device_console": "serial"}
          Sets the type of console to use
    [x] set
          {"device_console": "ssh"}
          Sets the type of console to use
    [x] wait
          {"duration": 2}
          Delays the execution of the next test/action for a set amount of time

Core tests (testsuite, Python):
    [ ] testsuite.filesystem.CheckFileSize
          No description
    [ ] testsuite.filesystem.FileExists
          No description
    [ ] testsuite.filesystem.FileIsBlockDevice
          No description
    [ ] testsuite.filesystem.FileIsCharDevice
          No description
    [ ] testsuite.filesystem.FileIsDir
          No description
    [ ] testsuite.filesystem.FileIsEmpty
          No description
    [ ] testsuite.filesystem.FileIsExecutable
          No description
    [ ] testsuite.filesystem.FileIsNotEmpty
          No description
    [ ] testsuite.filesystem.FileIsReadable
          No description
    [ ] testsuite.filesystem.FileIsRegular
          No description
    [ ] testsuite.filesystem.FileIsSocket
          No description
    [ ] testsuite.filesystem.FileIsSymlink
          No description
    [ ] testsuite.filesystem.FileIsWritable
          No description
    [x] testsuite.kernel.KernelModulesLoaded
          {"modules": ["wlan", "galcore"]}
          Verifies that a set of kernel modules are loaded
    [x] testsuite.memory.MemorySize
          {"total_mb": 985, "available_mb": 500}
          Tests the device's available and total memory
    [x] testsuite.networking.IperfBandwidth
          {"minimum_mbps": 10}
          Verifies the minimum bandwidth (in MBps)
    [x] testsuite.networking.RespondsToPing
          Verifies that there's a response to ping on the target

Inline tests (pluma.yml, Shell):
    [x] target_setup
          {"script": "echo \"setting things up on the target\"", "name": "target_setup"}
          Inline shell test
    [x] host_setup
          {"script": "echo \"setting things up locally\"", "run_on_host": true, "name": "host_setup"}
          Inline shell test
    [x] multiple_commands
          {"script": ["ls", "echo $USER"], "timeout": 2, "name": "multiple_commands"}
          Inline shell test
    [x] cat_meminfo
          {"script": "cat /proc/meminfo", "should_match_regex": ["MemFree:", "MemAvailable:"], "should_not_match_regex": ["error", "unknown"], "timeout": 2, "name": "cat_meminfo"}
          Inline shell test
    [x] cleanup
          {"script": "echo \"Cleaning up!\"", "name": "cleanup"}
          Inline shell test
```

2020-10-08 12:27 UTC, mjftw requested changes
It looks loads better having this test description output!
Some comments for change requests, mostly around improving output readability etc.

2020-10-08 12:27 UTC, mjftw commented on .gitignore
> +local-dev/
Is this .gitignore definitely needed?

2020-10-08 12:27 UTC, mjftw commented on pluma/cli/testsconfig.py
> +                log.log(f'          {test.description()}', level=log_level)
It would be nice to log the test description in another colour so that it stands out more in the console output.
Maybe yellow?

Or maybe just inserting a newline after each test description would make the output easier to read.

2020-10-08 12:27 UTC, mjftw commented on pluma/cli/testsconfig.py
> +    def print_tests_definition(tests: List[TestDefinition], log_level: LogLevel = None, detail_level: DetailLevel = None):
Style: This line is a little over the 100char limit

2020-10-08 12:27 UTC, mjftw commented on pluma/cli/testsconfig.py
> +        TestsConfig.print_tests_definition(self.tests, log_level=log_level, detail_level=detail_level)
Style: This line is a little over the 100char limit

2020-10-08 12:27 UTC, mjftw commented on pluma/core/baseclasses/logging.py
> +class DetailLevel(IntEnum):
Is this idea of DetailLevel definitely needed?
Would simplify the code if we only had a description for each test, without detail level filtering.

2020-10-08 12:27 UTC, mjftw commented on pluma/test/shelltest.py
> +    '''Inline shell test'''
I think in this case I might actually remove the test description for this one.
Reason being that on the console output for `pluma tests` it's repeated a bunch and doesn't really add any extra information.

```
Inline tests (pluma.yml, Shell):
    [x] target_setup
          {"script": "echo \"setting things up on the target\"", "name": "target_setup"}
          Inline shell test
    [x] host_setup
          {"script": "echo \"setting things up locally\"", "run_on_host": true, "name": "host_setup"}
          Inline shell test
    [x] multiple_commands
          {"script": ["ls", "echo $USER"], "timeout": 2, "name": "multiple_commands"}
          Inline shell test
    [x] cat_meminfo
          {"script": "cat /proc/meminfo", "should_match_regex": ["MemFree:", "MemAvailable:"], "should_not_match_regex": ["error", "unknown"], "timeout": 2, "name": "cat_meminfo"}
          Inline shell test
    [x] cleanup
          {"script": "echo \"Cleaning up!\"", "name": "cleanup"}
          Inline shell test
```

What would be nice is if we let the user specify a description for the inline shell test in the YAML file.
E.g.

```
- shell_tests:
    target_setup:
      description: Sets up the target 
      script: echo "setting things up on the target"
    host_setup:
      description: Sets up the host
      script: echo "setting things up locally"
      run_on_host: true
``` 

These would then be used as the description output in `pluma test`

2020-10-08 12:27 UTC, mjftw commented on pluma/cli/config.py
> +        desc = self.testclass.__doc__ or "No description"
Not sure if a test with no description should have it set to "No description", or just not have a description line printed in `pluma test`?
The advantage of "No description" is that it calls the user out for not putting a description, making it more likely that they will, but it doesn't tell them how.

I like the way that pytest handles this same thing with it's fixture view, calling out the specific line that the docstring is missing from, and highlighting it in red.

[See image here](https://ibb.co/fY7JYbP)

2020-10-08 12:43 UTC, mjftw commented on pluma/cli/config.py
> +        desc = self.testclass.__doc__ or "No description"
This should do it:
```python
In [1]: from inspect import getsourcefile, getsourcelines

In [2]: from pluma.plugins.testsuite.filesystem import FileIsSocket

In [3]: print(f'{getsourcefile(FileIsSocket)}:{getsourcelines(FileIsSocket)[1]} - missing docstring')
/home/merlin/projects/pluma-automation/pluma/plugins/testsuite/filesystem.py:53 - missing docstring
```

2020-10-09 21:43 UTC, Pixep commented on pluma/cli/testsconfig.py
> +                log.log(f'          {test.description()}', level=log_level)
Yellow is used for warnings, so I'm not sure? This would need to be before arguments however I think, instead of after.

2020-10-12 11:28 UTC, mjftw commented on pluma/cli/testsconfig.py
> +                log.log(f'          {test.description()}', level=log_level)
> Yellow is used for warnings, so I'm not sure? This would need to be before arguments however I think, instead of after.

Oh yeah good point.

2020-10-15 01:30 UTC, Zematus commented on .gitignore
> +local-dev/
not really, I moved that to my exclude file now

2020-10-15 01:31 UTC, Zematus commented on pluma/core/baseclasses/logging.py
> +class DetailLevel(IntEnum):
after the discussion, I think not. I removed it

2020-10-15 01:32 UTC, Zematus commented on pluma/cli/testsconfig.py
> +        TestsConfig.print_tests_definition(self.tests, log_level=log_level, detail_level=detail_level)
removed extra parameter

2020-10-15 01:32 UTC, Zematus commented on pluma/cli/testsconfig.py
> +    def print_tests_definition(tests: List[TestDefinition], log_level: LogLevel = None, detail_level: DetailLevel = None):
removed extra parameter

2020-10-15 02:40 UTC, Zematus commented on pluma/cli/testsconfig.py
> +                log.log(f'          {test.description()}', level=log_level)
I made a change so that only those tests that lack a description show "No description" in yellow as sort of a warning

2020-10-15 02:52 UTC, Zematus commented on pluma/test/shelltest.py
> +    '''Inline shell test'''
I was trying to implement something like this, but I though that maybe it's better to change the base description to "Execute given script within the target (or host) shell" because that describes exactly what the test will do. Besides, adding a description parameter would make the parameter list also display the description as an extra test parameter

2020-10-15 12:31 UTC, mjftw commented on pluma/test/shelltest.py
> +    '''Inline shell test'''
> I was trying to implement something like this, but I though that maybe it's better to change the base description to "Execute given script within the target (or host) shell" because that describes exactly what the test will do. Besides, adding a description parameter would make the parameter list also display the description as an extra test parameter

Yeah fair point. As much as it would be nice, I'm not sure it's needed, and it's not simple to implement (where do we put that extra info?).

We could still display the parameters and their types, since we have that information already.
That coupled with a good description should let a user know if the test does what they're after or not.

2020-10-15 12:36 UTC, mjftw commented on pluma/test/shelltest.py
> +    '''Execute given script within the target (or host) shell'''
Really minor one, but the sentence would read just as well with "given" removed.

2020-10-15 12:55 UTC, mjftw commented
For reference, how it currently looks. (we lose the colours here of course).

I think it's looking pretty good!
I like the newline between each of the test printouts, much easier to read.
The only thing I would say is that having the parameters for enabled tests and the descriptions together like that looks a bit confusing. 

```
(venv) merlin@pangolin:~/projects/pluma-automation$ pluma -c pluma.yml.sample -t pluma-target.yml tests

Device actions:
    [x] set
          {"device_console": "serial"}
          Sets the type of console to use

    [x] set
          {"device_console": "ssh"}
          Sets the type of console to use

    [x] wait
          {"duration": 2}
          Delays the execution of the next test/action for a set amount of time


Core tests (testsuite, Python):
    [ ] testsuite.filesystem.CheckFileSize
          No description

    [ ] testsuite.filesystem.FileExists
          No description

    [ ] testsuite.filesystem.FileIsBlockDevice
          No description

    [ ] testsuite.filesystem.FileIsCharDevice
          No description

    [ ] testsuite.filesystem.FileIsDir
          No description

    [ ] testsuite.filesystem.FileIsEmpty
          No description

    [ ] testsuite.filesystem.FileIsExecutable
          No description

    [ ] testsuite.filesystem.FileIsNotEmpty
          No description

    [ ] testsuite.filesystem.FileIsReadable
          No description

    [ ] testsuite.filesystem.FileIsRegular
          No description

    [ ] testsuite.filesystem.FileIsSocket
          No description

    [ ] testsuite.filesystem.FileIsSymlink
          No description

    [ ] testsuite.filesystem.FileIsWritable
          No description

    [x] testsuite.kernel.KernelModulesLoaded
          {"modules": ["wlan", "galcore"]}
          Verifies that a set of kernel modules are loaded

    [x] testsuite.memory.MemorySize
          {"total_mb": 985, "available_mb": 500}
          Tests the device's available and total memory

    [x] testsuite.networking.IperfBandwidth
          {"minimum_mbps": 10}
          Verifies the minimum bandwidth (in MBps)

    [x] testsuite.networking.NetworkingTestBase
          No description

    [x] testsuite.networking.RespondsToPing
          Verifies that there's a response to ping on the target


Inline tests (pluma.yml, Shell):
    [x] target_setup
          {"script": "echo \"setting things up on the target\"", "name": "target_setup"}
          Execute given script within the target (or host) shell

    [x] host_setup
          {"script": "echo \"setting things up locally\"", "run_on_host": true, "name": "host_setup"}
          Execute given script within the target (or host) shell

    [x] multiple_commands
          {"script": ["ls", "echo $USER"], "timeout": 2, "name": "multiple_commands"}
          Execute given script within the target (or host) shell

    [x] cat_meminfo
          {"script": "cat /proc/meminfo", "should_match_regex": ["MemFree:", "MemAvailable:"], "should_not_match_regex": ["error", "unknown"], "timeout": 2, "name": "cat_meminfo"}
          Execute given script within the target (or host) shell

    [x] cleanup
          {"script": "echo \"Cleaning up!\"", "name": "cleanup"}
          Execute given script within the target (or host) shell
```


One thing we could do for this is (cut down version for clarity):
```
(venv) merlin@pangolin:~/projects/pluma-automation$ pluma -c pluma.yml.sample -t pluma-target.yml tests

Device actions:
    [x] wait
          Delays the execution of the next test/action for a set amount of time
          Parameters:
               - duration: 2


Core tests (testsuite, Python):
    [ ] testsuite.filesystem.CheckFileSize
          No description - missing docstring
          Parameters:
              - path

    [ ] testsuite.filesystem.FileExists
          No description  - missing docstring
          Parameters:
              - path

Inline tests (pluma.yml, Shell):

    [x] multiple_commands
          Execute given script within the target (or host) shell
          Parameters:
              - script: ["ls", "echo $USER"]
              - timeout: 2
              - name: "multiple_commands"
          
    [x] cat_meminfo
          Execute given script within the target (or host) shell
          Parameters: 
              - script: "cat /proc/meminfo"
              - should_match_regex: ["MemFree:", "MemAvailable:"]
              - should_not_match_regex: ["error", "unknown"]
             -  timeout: 2
             -  name: "cat_meminfo"
```

Could even split it out into required and optional parameters, not sure.
I've also added " - missing docstring" to the no description bit, just so that users have a hint at how to fix the warning.

2020-10-17 23:08 UTC, Pixep requested changes

2021-01-07 22:27 UTC, prototypicalpro commented on pluma/test/shelltest.py
> +    '''Execute given script within the target (or host) shell'''
Fixed with 98b52e0486a34873de6186dfbabc919ec70cf94f.

2021-01-07 23:05 UTC, prototypicalpro commented on pluma/cli/config.py
> +        desc = self.testclass.__doc__ or "No description"
I added your code in 7d2cf078cadf94ee102358f01987140ee531e452. The output for a missing description now looks like this:
```console
[x] testsuite.networking.NetworkingTestBase
          No description - missing docstring at pluma/plugins/testsuite/networking.py:14 in NetworkingTestBase
```

2021-01-08 02:56 UTC, Pixep requested changes

2021-01-08 02:56 UTC, Pixep commented on pluma/utils/helpers.py
> +from typing import Tuple, Optional, Type, Any
`import` first, `from` then :)

2021-01-08 02:56 UTC, Pixep commented on pluma/utils/helpers.py
> +ROOT_PROJECT_DIRECTORY = os.path.normpath(os.path.join(_CUR_DIRECTORY, '../..'))
You may want to use the more recent `Path` class instead, with `Path.cwd()` and friends

2021-01-08 02:56 UTC, Pixep commented on pluma/utils/helpers.py
> +    rel_path = os.path.relpath(src_file, relative_to)
Same about using the `Path` class

2021-01-08 02:56 UTC, Pixep commented on pluma/cli/testsconfig.py
> -            if log_level == LogLevel.IMPORTANT:
I _think_ you need to keep the LogLevel here, its used to only display the description when that content is important. Did you have any reason to remove it?

2021-01-08 02:56 UTC, Pixep commented on pluma/cli/testsconfig.py
> +        if log_level is None:
Mh... I would argue here that `not value` is easier to read, and _I think_ the pythonic way of doing it. Less strict of course, but I don't know that it matters. Thoughts @mjftw ?

2021-01-08 02:56 UTC, Pixep commented on pluma/utils/helpers.py
> +def get_file_and_line(obj: Type[Any], relative_to: str = ROOT_PROJECT_DIRECTORY) -> Optional[Tuple[str, int]]:
Because we return a Tuple here, it might be safer to return a None Tuple instead of Optional, otherwise it will screw up code that is using it, which is unlikely to test for the return value. What do you think?

2021-01-08 02:56 UTC, Pixep commented on pluma/cli/config.py
> +    def description(self):
@prototypicalpro Could you incorporate these comments as well? Thank you :)

2021-01-08 02:56 UTC, Pixep commented on pluma/test/testbase.py
> +    def description(self):
@prototypicalpro Could you incorporate these comments as well? Thank you :)

2021-01-12 00:23 UTC, prototypicalpro commented on pluma/cli/testsconfig.py
> +        if log_level is None:
In this specific instance one possible value of `log_level` is `LogLevel.DEBUG = 0`, which is falsey and would create an unintended feature with the standard pythonic if statement.

2021-01-12 00:57 UTC, prototypicalpro commented on pluma/test/testbase.py
> +    def description(self):
It looks like you can't combine classmethod and property (lame), so I'll have to stick with just a classmethod.

2021-01-12 01:07 UTC, prototypicalpro commented on pluma/cli/testsconfig.py
> -            if log_level == LogLevel.IMPORTANT:
Is there a reason why that is switching off of the LogLevel, as opposed to a boolean parameter? If we're not sure I can leave it in.

2021-01-12 01:44 UTC, prototypicalpro commented on pluma/test/shelltest.py
> +    '''Inline shell test'''
Resolved with https://github.com/Witekio/pluma-automation/pull/137/commits/9c65fe5b6ded20d23c29d27afd9b4d01c75c667d where the test configuration is shown in YAML with the test description.

2021-01-12 19:21 UTC, prototypicalpro commented on pluma/cli/testsconfig.py
> -            if log_level == LogLevel.IMPORTANT:
I went ahead and did some digging, and fount two places where this statement mattered. The first one is in `execute_tests`: https://github.com/Witekio/pluma-automation/blob/0e26c783b80a37c14a6bff88177853ccdf1c908a/pluma/cli/api.py#L56-L64 and the second one is in `build_test_controller`: https://github.com/Witekio/pluma-automation/blob/0e26c783b80a37c14a6bff88177853ccdf1c908a/pluma/cli/api.py#L117-L123

It looks to me (feel free to correct me) that the intention was to have a verbose output with `pluma tests` and a less verbose output with `pluma check`, and this behavior was switched using the `log_level` parameter. Since these are the only two places where `print_tests_definition` is called, I went ahead and refactored this functionality into a `show_description` keyword argument in the print tests function to make this behavior more clear.

2021-01-12 19:38 UTC, Pixep approved these changes
Good for me. @mjftw ?

2021-01-12 19:38 UTC, Pixep commented on pluma/cli/api.py
> +        tests_config.print_tests(log_level=LogLevel.IMPORTANT, show_description=True)
Okay nice. Man I get confused everytime with the name of the method... its a bad name. Its the name of the CLI command, `tests`, but... nah. Anyway, yes that works 👍

2021-01-13 09:58 UTC, mjftw commented on pluma/cli/api.py
> +        tests_config.print_tests(log_level=LogLevel.IMPORTANT, show_description=True)
Nice solution with clearer intent.

2021-01-13 10:13 UTC, mjftw approved these changes
This is looking really good!

My only comment is really very minor so approving; feel free to merge.

2021-01-13 10:13 UTC, mjftw commented on pluma/cli/testsconfig.py
> +                    log.log(f'          {description}', level=log_level)
Very picky point here, and I'm not going to block merging on this.

Would be better to not have an explicit load of spaces here before every bit of info to be printed.
I believe the intent is to print with indentation at different levels, and if this is the case we could do something like:

```python
indent = '     '

log.log(f'{indent}Message with indentation')
log.log(f'{indent*2}Message with double indentation')
log.log(f'{indent*3}Message with triple indentation')
```
_______________________________________________

Or if this is a general thing that we may want to do all over the place when we log (and I think it is), we could put this code inside the logger and have an indentation parameter for the log functions.

E.g.
```python
log.log(f'{description}', level=log_level, indent=2)
```

This is of course a more complicated solution though, and would require us to create (via inheritance) a modified version of the standard Python logger to use. Complexity is a bad thing, so maybe this idea is too.

2021-01-13 10:13 UTC, mjftw commented on pluma/cli/testsconfig.py
> +                    log.log('', level=log_level)
What is this empty log for?

2021-01-14 18:25 UTC, prototypicalpro commented on pluma/cli/testsconfig.py
> +                    log.log('', level=log_level)
To add a trailing newline:
```console
    [x] testsuite.networking.NetworkingTestBase
    [x] testsuite.networking.RespondsToPing
         < --- this one
Inline tests (pluma.yml, Shell):
    [x] target_setup
```

2021-01-14 18:51 UTC, prototypicalpro commented on pluma/cli/testsconfig.py
> +                    log.log(f'          {description}', level=log_level)
Would https://github.com/Witekio/pluma-automation/pull/137/commits/4a8924be9cdb51dab59b1d84f592930fdf1e39d5 be what you are looking for? I'm not sure what you are referring to regarding the modified version of the python logger.

2021-01-15 14:07 UTC, mjftw commented on pluma/cli/testsconfig.py
> +                    log.log(f'          {description}', level=log_level)
Oh yeah perfect, that's exactly what I was after!

2021-01-15 14:09 UTC, mjftw approved these changes
This is looking great!

A few things to tidy up as found in the Codacy Static Code Analysis (CI step below), then good to merge 👍🏼 
https://app.codacy.com/gh/Witekio/pluma-automation/pullRequest?prid=6303685

2021-01-18 23:42 UTC, Pixep commented
Good to go, only static type check failed, as expected.

2021-01-18 23:42 UTC, merged