Feature/refactor testrunner
Witekio/pluma-automation pull request #154
Opened 2020-10-12 19:04 UTC by mjftw

Lots of changes to TestRunner, and lots more tests.
I've also made `board` optional in both `TestRunner` and `TestBase`, since it's not actually really needed; should make classes more flexible.
I also found and fixed a bug along the way, but I may have caused it in my refactoring, not sure.

2020-10-12 20:13 UTC, Pixep commented on pluma/test/testrunner.py
> +                self.board.release_log()
`release_log` should occur regardless of if you have a board or not, and probably be `self.release_log()` actually :). Probably a miss. I don't know if its the right time to move to `log.log()` functions, as you are changing those?

2020-10-12 20:15 UTC, Pixep commented
Great, happy we can clean all of those for a fresh start. Only 1 check ran, and I don't know if the target branch if the right one (?). Will review a bit more in depth, but looks pretty cool

2020-10-12 21:43 UTC, mjftw commented
> Great, happy we can clean all of those for a fresh start. Only 1 check ran, and I don't know if the target branch if the right one (?). Will review a bit more in depth, but looks pretty cool

Fixed it, looks like the checks have run now 👍🏼

2020-10-13 01:23 UTC, Pixep commented on pluma/test/testrunner.py
> +            self.add_test(test)
So doing `tests = x` if effectively doing something like `tests += x` actually right? Is that wanted?

2020-10-13 01:24 UTC, Pixep commented on pluma/test/testrunner.py
> +            self.board.hold_log()
Same comment as `release_log`

2020-10-13 14:15 UTC, mjftw commented on pluma/test/testrunner.py
> +            self.add_test(test)
Ooooooooooops 👍🏼. Fixed.

2020-10-13 14:15 UTC, mjftw commented on pluma/test/testrunner.py
> +            self.board.hold_log()
Fixed

2020-10-14 20:44 UTC, Pixep requested changes
Only one important change for `release_log`

2020-10-14 20:44 UTC, Pixep commented on pluma/test/testrunner.py
>              self.board.release_log()
`self.release_log()` here if you want to match the `self.hold_log()` you have above

2020-10-14 20:44 UTC, Pixep commented on pluma/test/testrunner.py
> +    def _failed_task_side_effects(self, test: TestBase, task_name: str, exception: Exception):
nit: I actually maybe preferred the older name, which was a verb. I guess this could be `_on_task_failed` or `_run_task_failed_side_effects`, or the original too. This one could be read as just "get" the side effects. But that's not super important.

2020-10-14 20:44 UTC, Pixep commented on pluma/test/testrunner.py
> +class TestRunnerParallel(TestRunnerBase):
Out of curiosity, this one isn't used yet, right?

2020-10-19 15:00 UTC, mjftw commented on pluma/test/testrunner.py
>              self.board.release_log()
Oops! Fixed

2020-10-19 15:00 UTC, mjftw commented on pluma/test/testrunner.py
> +    def _failed_task_side_effects(self, test: TestBase, task_name: str, exception: Exception):
Yeah fair point, went with the old name

2020-10-19 15:00 UTC, mjftw commented on pluma/test/testrunner.py
> +class TestRunnerParallel(TestRunnerBase):
Nope, we could remove it entirely tbh

2020-10-19 17:37 UTC, Pixep approved these changes
Good to go!

2020-10-22 14:39 UTC, mjftw commented
> Good to go, once the pipeline is fixed :)
> 
> ```
> _______________ ERROR collecting generic/test/test_TestRunner.py _______________
> import file mismatch:
> imported module 'test_TestRunner' has this __file__ attribute:
>   /home/runner/work/pluma-automation/pluma-automation/tests/generic/core/test_TestRunner.py
> ```

I had a look and tried to work this out, but I'm really not sure what's causing it...
Doesn't happen on my machine

2020-11-05 12:18 UTC, merged