tests: add ExecutableTest constructor coverage
Witekio/pluma-automation pull request #157
Opened 2020-10-13 04:25 UTC by Pixep

2020-10-15 23:01 UTC, Pixep commented
Started refactoring the executable test, more to be done to move that to a base class/module. Sweet 100% coverage on it now, though that doesn't necessarily means much.

2020-10-16 10:08 UTC, mjftw requested changes
Looks like some good changes and always keen for more unit tests.
Some comments about possible other ways of doing this with less code.

2020-10-16 10:08 UTC, mjftw commented on tests/generic/test/test_ExecutableTest.py
> +    target_executable = os.path.join(target_tmp_dir, 'myapp')
Better to use more modern pathlib.Path in new code.
```python
target_executable = pathlib.Path(target_tmp_dir)/'myapp'
```

2020-10-18 22:18 UTC, Pixep commented on pluma/test/executabletest.py
> +                ' was defined or set. Define a console in "pluma-target.yml", or use '
Done

2020-10-18 22:23 UTC, Pixep commented on pluma/test/executabletest.py
> +                          command=f'mkdir {temp_folder}',
This is all on the target, so I don't believe we can actually use any of this :)

2020-10-18 22:26 UTC, Pixep commented on pluma/test/executabletest.py
> +        destination = os.path.join(temp_folder,
Gave it a try, but this is all older code, and all the rest of the classes uses os.path consistently. Changing it would likely require changing all of these, and converting it to `str()` for external functions we are calling. Probably better in a different ticket. I did use pathlib.Path() in the new FileBuilder classes though.

2020-10-18 22:33 UTC, Pixep commented on tests/generic/test/test_ExecutableTest.py
> +    target_executable = os.path.join(target_tmp_dir, 'myapp')
Done

2020-10-19 12:54 UTC, mjftw commented on pluma/test/executabletest.py
> +        destination = os.path.join(temp_folder,
I'll put an issue up about moving over at some point

2020-10-19 12:55 UTC, mjftw commented on pluma/test/executabletest.py
> +                          command=f'mkdir {temp_folder}',
Oooooh hadn't realised. Yeah of course it is, my bad!

2020-10-19 12:59 UTC, mjftw approved these changes
Looking good!

2020-10-19 12:59 UTC, merged