Feature/improve test builder
Witekio/pluma-automation pull request #160
Opened 2020-10-16 03:44 UTC by Pixep

Architectural step towards supporting CMake (and other) builders

2020-10-16 10:37 UTC, mjftw requested changes
Code all looks good. Definitely a step forward for architecture!
Only comments are super minor and are about using `pathlib` over `os.path`.

2020-10-16 10:37 UTC, mjftw commented on pluma/cli/testsbuilder.py
> +        return os.path.join(self.install_dir, self.target_name)
Better to use more modern pathlib over `os.path` for new code:
https://docs.python.org/3/library/pathlib.html

2020-10-16 10:37 UTC, mjftw commented on pluma/cli/testsbuilder.py
> +            os.makedirs(directory, exist_ok=True)
pathlib can do this too: https://docs.python.org/3/library/pathlib.html#pathlib.Path.mkdir

2020-10-16 10:37 UTC, mjftw commented on pluma/cli/testsbuilder.py
> +        self.install_dir = os.path.abspath(install_dir)
pathlib can do this, although not sure where it's documented.
https://stackoverflow.com/questions/42513056/how-to-get-absolute-path-of-a-pathlib-path-object

2020-10-16 10:37 UTC, mjftw commented on pluma/cli/testsbuilder.py
> +        log.debug(f'Build command = {self.build_command}')
May not be appropriate here but mentioning as it's a cool new feature in Python 3.8 that is related to this and is good to be aware of:

https://docs.python.org/3/whatsnew/3.8.html#f-strings-support-for-self-documenting-expressions-and-debugging

2020-10-16 10:37 UTC, mjftw commented on pluma/cli/testsbuilder.py
> +            if not force:
Nice to ask :)

2020-10-18 00:17 UTC, Pixep commented on pluma/cli/testsbuilder.py
> +        return os.path.join(self.install_dir, self.target_name)
Done

2020-10-18 00:18 UTC, Pixep commented on pluma/cli/testsbuilder.py
> +            os.makedirs(directory, exist_ok=True)
Done

2020-10-18 00:19 UTC, Pixep commented on pluma/cli/testsbuilder.py
> +        self.install_dir = os.path.abspath(install_dir)
Done. Went for `resolve()` that I found in the doc, and SO seems to confirm that's the wtg.

2020-10-18 00:20 UTC, Pixep commented on pluma/cli/testsbuilder.py
> +        log.debug(f'Build command = {self.build_command}')
Neat! We're compatible down to 3.6 though, so not really usable here.

2020-10-19 14:48 UTC, mjftw reviewed
Good to go

2020-10-19 14:49 UTC, mjftw approved these changes
Missed pressing the Approve button on the last review!

2020-10-19 17:50 UTC, merged