Fix most config related typing issues
Witekio/pluma-automation pull request #175
Opened 2021-01-11 00:46 UTC by Pixep

Add typed and optional versions of the configuration 'pop' function

2021-01-11 12:13 UTC, mjftw requested changes
This is looking really good! Great to see all this lovely type info.

I've added a couple of suggestions for small improvements, mostly just to reduce duplication and allow us to cut a fair bit of code out.

2021-01-11 12:13 UTC, mjftw commented on pluma/cli/config.py
> +    def pop_optional_str(self, attribute: str, default: Optional[str] = None,
Very nice to see type safe versions of these functions to do input validation 👍🏼 

My only suggestion for improvement would be that some of the duplication here could be reduced, perhaps by passing in the type.
We'd maybe end up with something like:

```python
from typing import Optional, TypeVar

T = TypeVar('T')

# (the current pop function could be renamed pop_unsafe, or this one be called pop_safe)
def pop(self, datatype: T, attribute: str, context: Optional[str] = None):
    value = self.pop_optional(attribute, datatype, context=context)
    if value is None:
        self.__raise_error(f'missing required {datatype.__name__} attribute "{attribute}"', context)

    return value

def pop_optional(self, datatype: T, attribute: str, default: Optional[T] = None,
                 context: Optional[str] = None) -> Optional[T]:
    value = self.pop_raw(attribute, default)
    if value is not None and not isinstance(value, datatype):
        self.__raise_error(f'attribute "{attribute}" should be a {datatype.__name__} '
                            f'but got "{value}"', context)
    return value
```

That way the typed calls would like like:

```python
self.pop(bool, my_boolean_name)
# and
self.pop_optional(str, my_str_name, "Hello world!")
```

Could also do this by passing in a predicate function to be used to evaluate whether the value read is valid or not, but this way you don't have the type information to print in the `__raise_error()` call.

E.g. that would look like
```python
def pop(..., predicate: Callable[[any], bool]], ...):
    value = get_the_value()
    if not predicate(value):
        # error handling
    ...
```

And the call site would look like:
```python
self.pop('foo_bar', lambda x: isinstance(x, bool), ...)
```
This would handle special requirements for type checking (E.g. like you're doing with int), but I think it's much uglier.


Anyway, not a hard requirement to abstract this but might make it cleaner.

2021-01-11 12:13 UTC, mjftw commented on pluma/cli/config.py
> +    def first(self) -> str:
For stuff like this where it might raise an exception, we could use type
```
def first(self) -> Union[str, NoReturn]:
    ....
```

This would indicate that the function may not exit with a value at all, but don't know if this is more or less readable?

2021-01-11 12:13 UTC, mjftw commented on pluma/core/builder/yoctocbuilder.py
> +            raise Exception('install_dir must be a Path')
I'd probably go for a `TypeError` here rather than a bare `Exception`.

2021-01-11 17:04 UTC, Pixep commented on pluma/cli/config.py
> +    def pop_optional_str(self, attribute: str, default: Optional[str] = None,
That's a good point yes. I wanted to go in that direction somehow but kept it simple for now. That should be an easy change to make

2021-01-11 17:04 UTC, Pixep commented on pluma/cli/config.py
> +    def first(self) -> str:
Mhh I have never seen that, is that a common way of expressing that an exception can be raised?

2021-01-11 17:05 UTC, Pixep commented on pluma/core/builder/yoctocbuilder.py
> +            raise Exception('install_dir must be a Path')
👍

2021-01-12 19:34 UTC, prototypicalpro commented on pluma/cli/config.py
> +    def first(self) -> str:
It looks like the docstring of the function is the only way, as the typing system [doesn't support it](https://www.python.org/dev/peps/pep-0484/#exceptions).

2021-01-12 20:28 UTC, prototypicalpro requested changes
One error with pylance I can mention:
https://github.com/Witekio/pluma-automation/blob/fe125d87520acb351bfecd5a4d25fe475ae460e1/pluma/cli/config.py#L239 For some reason pylance doesn't recognize `yaml.parser.ParserError`, but it does recognize `from yaml.parser import ParserError`. Not sure if that's a bug or a python thing.

2021-01-12 20:28 UTC, prototypicalpro commented on pluma/cli/deviceactionregistry.py
> +    def register_class(cls, action_class: Type, action_key: str):
You can specialize `Type` to indicate that `action_class` should be or inherit from `DeviceActionBase`:
```suggestion
    def register_class(cls, action_class: Type[DeviceActionBase], action_key: str):
```

Note that if you want to keep the subclass error check you'll need to replace `action_class.__name__` with `cast(Type, action_class).__name__` to make the type system happy.

2021-01-12 20:28 UTC, prototypicalpro commented on pluma/cli/config.py
> +    def pop_optional_str(self, attribute: str, default: Optional[str] = None,
For `pop_optional`, we could do something like this to ensure the return type isn't optional when the default keyword is specified:
```python
    def pop_optional(self, datatype: Type[T], attribute: str, default: D = None,
                 context: Optional[str] = None) -> Union[T, D]:
        value = self.pop_raw(attribute, default)
        if value is None or not isinstance(value, datatype):
            self.__raise_error(f'attribute "{attribute}" should be a {datatype.__name__} '
                                f'but got "{value}"', context)
        return value
```

Note that for pylance I can't get it to resolve the generics D and T correctly, but I'd be curious if it's better with the other tools.

2021-01-14 19:39 UTC, prototypicalpro commented on pluma/cli/config.py
> +    def pop_optional_str(self, attribute: str, default: Optional[str] = None,
Here's an updated version that resolves the types correctly in pylance. I ended up having to create some overload stubs to deal with the type of default so it's a bit uglier, but it should result in less unnecessary None checks when using `pop_optional`.

```python
    # Type if default is None
    @overload
    def pop_optional(self, datatype: Type[T], attribute: str, default: None = None, context: Optional[str] = None) -> Optional[T]: ...
    # Type if default is a non-None value
    @overload
    def pop_optional(self, datatype: Type[T], attribute: str, default: D, context: Optional[str] = None) -> Union[T, D]: ...
    # Implementation
    def pop_optional(self, datatype: Type[T], attribute: str, default: Optional[D] = None,
                 context: Optional[str] = None) -> Union[T, Optional[D]]:
        value = self.pop_raw(attribute, default)
        if not isinstance(value, datatype) and not isinstance(value, type(default)):
            self.__raise_error(f'attribute "{attribute}" should be a {datatype.__name__} '
                                f'but got "{value}"', context)
        return cast(Union[T, D], value)
```

2021-01-15 22:53 UTC, Pixep commented on pluma/cli/config.py
> +    def first(self) -> str:
I agree for a function that never returns anything, or sometimes does not. But any function has the potential to throw if something goes wrong, i.e. all functions need `Union[xxx, NoReturn]`, which would in return provides no added value. So in this situation, I don't see a point in adding it. Different opinions?

2021-01-19 00:07 UTC, Pixep commented on pluma/cli/ctestsprovider.py
>          if not config:
Yes, I think I will go over all providers in a different PR, to not overwhelm it more than it is :)

2021-01-19 00:28 UTC, Pixep commented on pluma/cli/deviceactionregistry.py
> +    def register_class(cls, action_class: Type, action_key: str):
Done

2021-01-19 01:47 UTC, Pixep commented on pluma/cli/ctestsprovider.py
>              install_dir = YoctoCBuilder.install_yocto_sdk(toolchain_file)
Yeah I can't because we need one or the other. In this branch, toolchain_file has to be set (otherwise we go in the one above.

2021-01-19 02:22 UTC, Pixep commented on pluma/cli/config.py
> +    def pop_optional_str(self, attribute: str, default: Optional[str] = None,
Thank you both for your help, done :)

2021-01-19 17:02 UTC, Pixep commented
Down from 2xx to 157 errors for the type checking

2021-01-19 17:17 UTC, prototypicalpro commented on pluma/cli/ctestsprovider.py
>              install_dir = YoctoCBuilder.install_yocto_sdk(toolchain_file)
Alright, in that case a cast will get rid of the error:
```suggestion
            install_dir = YoctoCBuilder.install_yocto_sdk(cast(str, toolchain_file))
```

2021-01-19 17:36 UTC, prototypicalpro commented on pluma/cli/config.py
> +    def pop_optional_str(self, attribute: str, default: Optional[str] = None,
Something I just realized is that python has a `MutableMapping` base class that implements `popitem` on top of abstract methods: https://docs.python.org/3/library/collections.abc.html#collections-abstract-base-classes. We may want to switch to this implementation since it is definitely the more pythonic way of doing things, but on the other hand if we switch it will require another decent refactor (replace `pop_optional` with `popitem`).

2021-01-19 17:41 UTC, Pixep commented on pluma/cli/ctestsprovider.py
>              install_dir = YoctoCBuilder.install_yocto_sdk(toolchain_file)
Yes right, done.

2021-01-19 17:41 UTC, prototypicalpro commented on pluma/cli/config.py
> +    def pop_optional_str(self, attribute: str, default: Optional[str] = None,
On second pass, it looks like `popitem` doesn't perform any type checking, which is a beneficial aspect of `pop_optional`. Perhaps we could rename `pop_optional` to `popitem_typechecked` (or similar) and have it coexist with `popitem`?

2021-01-19 17:50 UTC, Pixep commented on pluma/cli/config.py
> +    def pop_optional_str(self, attribute: str, default: Optional[str] = None,
AFAIS, popitem is unrelated, and meant to pop a key value pair in a LIFO fashion.

2021-01-19 17:55 UTC, Pixep commented on pluma/cli/config.py
> +    def pop_optional_str(self, attribute: str, default: Optional[str] = None,
Okay, just had another look at it: we may bring them closer, but its going to take more than a few minutes I think, to ponder the implications. I would recommend avoiding pushing to much in that one PR.

2021-01-21 15:17 UTC, mjftw approved these changes
Really nice work, this is looking great!

2021-01-21 17:38 UTC, prototypicalpro approved these changes
Lgtm!

2021-01-21 17:44 UTC, merged