Expose power controllers reboot_delay in target config
Witekio/pluma-automation pull request #177
Opened 2021-01-11 15:40 UTC by mjftw

2021-01-11 18:17 UTC, Pixep requested changes

2021-01-11 18:17 UTC, Pixep commented on pluma/cli/targetconfig.py
> +        reboot_delay = power_config.pop('reboot_delay')
@mjftw Could you add a quick mention in the documentation?

2021-01-11 18:22 UTC, mjftw commented on pluma/cli/targetconfig.py
> +        reboot_delay = power_config.pop('reboot_delay')
We've actually not got a section in the docs about the power controllers in the target file at all.
Rather than adding it all now, do you mind if we create a new issue to add this info (for all power controllers)?

2021-01-12 19:29 UTC, Pixep requested changes

2021-01-12 19:29 UTC, Pixep commented on pluma/cli/targetconfig.py
> +import re
Wait... that's not used, is it?

2021-01-13 10:29 UTC, mjftw commented on pluma/cli/targetconfig.py
> +import re
Oops. Automatic imports can be really useful, but also not so good sometimes.

2021-01-13 10:31 UTC, mjftw commented on pluma/cli/targetconfig.py
> +import re
Fixed.

2021-01-13 22:56 UTC, Pixep approved these changes
G2G!

2021-01-13 22:57 UTC, merged