Feature/prepare for pypi push
Witekio/pluma-automation pull request #178
Opened 2021-01-11 17:03 UTC by mjftw

Once merged, this PR should mean that every push to master also pushes a new python distribution package to Pypi.

2021-01-12 10:24 UTC, mjftw commented on setup.py
>      author_email='mwebster@witekio.com',
FYI on this one, in order to push to Pypi I need a single email address to go here.
Ideally this would also be an email address that users could contact to get support, so currently put mine down but there may be something better. Maybe an email group at Witekio like pluma-dev@witekio.com which we're all on?
That would mean we don't have to update Pypi if I were to get hit by a bus or something.

2021-01-12 19:24 UTC, Pixep commented on setup.py
>      author_email='mwebster@witekio.com',
Yes good idea. That would be an IT ticket I believe...?

2021-01-12 19:26 UTC, Pixep requested changes
Just one question regarding publishing only if all succeeds

2021-01-12 19:26 UTC, Pixep commented on .github/workflows/bump-version-and-publish-to-pypi.yml
> +name: Version tag bump and publish to PyPI
Is there a way to run that _only_ if the CI passes on master? To prevent/catch issues

2021-01-13 10:21 UTC, mjftw commented on .github/workflows/bump-version-and-publish-to-pypi.yml
> +name: Version tag bump and publish to PyPI
That's a very good idea.

The difficulty here is that for the push to PyPi to happen, we need to have bumped the version tag to something proper else it will get rejected. As far as I could see (from a few mins of googling) there's no way to make one Github Action depend on another, and the expected way is to do it all with different jobs in the same action. It's for this reason that I've put the publish CI in the same Action as the tagging job.
If we can't make one Action/Workflow depend on another then the only way to do your suggestion would be to do the tag and push in the same Action/Workflow as all of the other CI checks we want to go before, which is a bit messy and quite a big change.
Also, if commits are merged to master we do _need_ there to be a new version tag, else it's impossible to know where one feature changeset ends and another begins (because we are doing rebase merges).

The counter argument to this need would be, if the CI passed on the pull request to master, but failed when merged to master, does that not mean that the issue is with the CI and merging strategy rather than the code under test?

2021-01-13 10:28 UTC, mjftw commented on setup.py
>      author_email='mwebster@witekio.com',
IT ticket raised

2021-01-13 22:48 UTC, Pixep commented on .github/workflows/bump-version-and-publish-to-pypi.yml
> +name: Version tag bump and publish to PyPI
> The counter argument to this need would be, if the CI passed on the pull request to master, but failed when merged to master, does that not mean that the issue is with the CI and merging strategy rather than the code under test?

If we only do fast forward yes. Maybe that is the easy answer: no rebase from GitHub, only fast forwards :)

2021-01-13 22:55 UTC, Pixep approved these changes
Good to go

2021-01-14 08:03 UTC, mjftw commented on .github/workflows/bump-version-and-publish-to-pypi.yml
> +name: Version tag bump and publish to PyPI
Good idea.
Since we'll be relying on people don't the right kind of merges, I'll change the settings to enforce that

2021-01-14 08:26 UTC, merged