Console: fix type hints issues in console related files
Witekio/pluma-automation pull request #187
Opened 2021-01-19 22:04 UTC by Pixep

Removes another 40-ish type hints warnings

2021-01-19 22:15 UTC, prototypicalpro requested changes
Some minor typing fixes. Good to see the type error count come down!

2021-01-19 22:15 UTC, prototypicalpro commented on pluma/core/baseclasses/consolebase.py
>                         start_bytes: int = None) -> bool:
The `int` type is included in the `float` type:
```suggestion
    def wait_for_bytes(self, timeout: Optional[float] = None,
                       sleep_time: Optional[float] = None,
                       start_bytes: Optional[int] = None) -> bool:
```

2021-01-19 22:15 UTC, prototypicalpro commented on pluma/core/baseclasses/consolebase.py
> +                      quiet_time: Union[int, float] = None,
```suggestion
    def send_and_read(self, cmd: str, timeout: Optional[float] = None,
                      sleep_time: Optional[float] = None,
                      quiet_time: Optional[float] = None,
```

2021-01-19 23:27 UTC, Pixep commented on pluma/core/baseclasses/consolebase.py
>                         start_bytes: int = None) -> bool:
Haha of course...😌 thanks

2021-01-19 23:27 UTC, Pixep commented on pluma/core/baseclasses/consolebase.py
> +                      quiet_time: Union[int, float] = None,
Done

2021-01-20 09:44 UTC, mjftw reviewed
This is looking like a big improvement, thanks!
Do you think we'd be able to find away around that implicit float conversion line? (`x = x * 1.0`)

2021-01-20 09:44 UTC, mjftw commented on pluma/core/baseclasses/consolebase.py
> +            timeout = timeout*1.0
Is this to force float conversion?

If so I'm guessing it's here to keep the type checker happy?
I can see why you'd do it, but it does obfuscate the code a little.

2021-01-20 09:44 UTC, mjftw commented on pluma/core/baseclasses/pexpectengine.py
> +        text_matched = self.decode(matched_text) if matched_text else None
Good spot! Shouldn't be decoding this if it's None.

2021-01-20 09:44 UTC, mjftw commented on tests/generic/core/test_PexpectEngine.py
> +def test_PexpectEngine_error_on_control_longer_than_one_char(pty_pair_raw):
Aaah yeah good test to add, didn't think to add that one

2021-01-20 09:46 UTC, mjftw commented on pluma/core/baseclasses/consolebase.py
> +            timeout = timeout*1.0
Just making it more explicit what we're doing might be enough if there's no way to keep the type checker happy otherwise.
```python
if timeout is not None:
    timeout = float(timeout)
```

2021-01-20 19:15 UTC, Pixep commented on pluma/core/baseclasses/pexpectengine.py
> +        text_matched = self.decode(matched_text) if matched_text else None
It was previously accepting `None`, and working fine. But in the end the type check was being a bit annoyed by it, so I changed the way this works :)

2021-01-20 19:16 UTC, Pixep commented on pluma/core/baseclasses/consolebase.py
> +            timeout = timeout*1.0
Yes that's now better, I was able to revert to the original form, now that the input type is only `Optional[float]`. Before this wasn't possible. Fixed.

2021-01-21 15:32 UTC, mjftw approved these changes
Looking great, merging 👍🏼

2021-01-21 15:35 UTC, merged