Fix/more type hints
Witekio/pluma-automation pull request #192
Opened 2021-01-22 05:31 UTC by Pixep

Clear all remaining errors except a couple, and a few files which we have to choose to drop, or refactor.
CI passing for type check.

2021-01-22 05:33 UTC, Pixep commented on pluma/utils/helpers.py
> -def format_json_tinydb(db_file, db_output_file):
dropped, as unused

2021-01-22 05:34 UTC, Pixep commented on pluma/core/baseclasses/powerbase.py
> +def power_on(f):
These were messed up, actually `abstractmethod` which were also decorators, both with different signatures.

2021-01-23 08:23 UTC, mjftw requested changes
This is looking so much better, and I can see a load of genuine possible bugs that were fixed while doing this :)
Nice one putting the effort in for this. I know fixing compiler errors can be a bit dull.

Some comments below.

2021-01-23 08:23 UTC, mjftw commented on pluma/test/testrunner.py
> +        self.tests = tests  # type: ignore
??

2021-01-23 08:23 UTC, mjftw commented on pluma/utils/email.py
> +# TODO: Drop file, or fix type check
??

2021-01-23 08:23 UTC, mjftw commented on pluma/utils/git.py
> +        # TODO: Are we sure [0] is never None?
Yeah, we can be pretty confident of that at this point since the previous block ensures that.

```python
    if None in filtered_versions_lists:
        return None
        return None
```

2021-01-23 08:23 UTC, mjftw commented on pluma/utils/git.py
> +        filtered_versions = set(filtered_versions_lists[0])  # type: ignore
I don't really like having all these `#type: ignore` bits in here (or anywhere really).
Feels like if we can't fix all the type errors right now then we should just let these lines fail and fix them later, rather than artificially making it look like there are no errors, otherwise it's unlikely we'll ever remember these are here and they'll never get fixed.
My other reason for disliking them is that they're at a completely different level of abstraction/ purpose than all of the code around them, which hurts readability and is bad for single responsibility principle. I'm not a fan of all inline external tool pragmas (which is pretty much what this is) for this reason.

I can see why you'd stick them in to try to get the type check passing, but maybe better to let it fail for now.

2021-01-23 08:23 UTC, mjftw commented on pluma/utils/helpers.py
> -def format_json_tinydb(db_file, db_output_file):
I think this was used by a user of the Pluma library (a different project) rather than the library itself.
You could make the argument that it belongs in the other project should be implementing this though if it doesn't really have any baring on Pluma.

2021-01-23 08:23 UTC, mjftw commented on pluma/utils/helpers.py
> -def format_json_tinydb(db_file, db_output_file):
Oh yeah I remember, this was used extensively for persisting results in another project and was very useful.
We can drop it here though.

2021-01-23 08:23 UTC, mjftw commented on tests/generic/core/test_PowerMulti.py
> +    @power_on
See notes in `powerbase.py`

2021-01-23 08:24 UTC, mjftw commented
> Clear all remaining errors except a couple, and a few files which we have to choose to drop, or refactor:
> 
>     * hub.py, modem.py, pdu.py, email.py
> 
> 
> CI passing for type check.
> 
> @mjftw: Do you have an opinion on these?

What's it complaining about?

The reason for these files is to allow the import paths to be shorter by making the deeper functions/classes/... accessible at the higher levels.

2021-01-24 00:42 UTC, Pixep commented
> What's it complaining about?
> 
> The reason for these files is to allow the import paths to be shorter by making the deeper functions/classes/... accessible at the higher levels.

> This is looking so much better, and I can see a load of genuine possible bugs that were fixed while doing this :)
> Nice one putting the effort in for this. I know fixing compiler errors can be a bit dull.
> 
> Some comments below.

To explain my reasoning here: I am pretty much convinced at this point that we **need** a OK/NOK from the CI **now**, as this proved super useful for me when implementing the next TestGroup classes, to catch errors, and we need it given the size of the code base, as we reachitecture parts and bits of it. But this **only** works if the output is clean, if there are no errors reported. Otherwise, we won't bother checking the output, its too painful, and we won't know what was an error before, and what's new, because type errors can show up in any files anyway. That's why I want to reach "0 errors" ASAP, even if this means hiding some, and creating tickets to fix them.

Regarding these 4 files, these are older files, that have tons of typing errors. I probably fixed ~150 alone, but can't really spend more time addressing these, because I know these classes less, and I don't know if they are/will be useful after our merge.

So the best way to have the typecheck available for you/Noah/myself, is to ignore those ~50 remaining errors, to let us focus on what matters, and create tasks to either fix these issues (if the classes will be used) or drop the related code, if it won't be used.

I added the `make validate` as well, which ensures pyright and unit tests pass, which catches so many issues, but again, the output needs to be clean for that.

2021-01-24 00:43 UTC, Pixep commented on pluma/utils/helpers.py
> -def format_json_tinydb(db_file, db_output_file):
Ok, its still in Git if needed too :)

2021-01-24 00:58 UTC, Pixep commented on pluma/core/baseclasses/powerbase.py
> +def power_on(f):
Yeah that's actually what I wanted to do, but I thought you wouldn't like it, not sure its the pythonic way of doing this :). But well, its in now!

2021-01-24 00:59 UTC, Pixep commented on pluma/core/baseclasses/powerbase.py
> +        '''Turn on the power controll'''
Done

2021-01-24 00:59 UTC, Pixep commented on pluma/core/baseclasses/relaybase.py
> +def relay_toggle(f):
Done

2021-01-24 00:59 UTC, Pixep commented on pluma/core/baseclasses/powerbase.py
> +        '''Turn off the power controll'''
Done

2021-01-28 10:43 UTC, mjftw commented on pluma/core/baseclasses/powerbase.py
> +def power_on(f):
Oh okay cool :D

2021-01-28 10:51 UTC, mjftw commented
> > What's it complaining about?
> > The reason for these files is to allow the import paths to be shorter by making the deeper functions/classes/... accessible at the higher levels.
> 
> > This is looking so much better, and I can see a load of genuine possible bugs that were fixed while doing this :)
> > Nice one putting the effort in for this. I know fixing compiler errors can be a bit dull.
> > Some comments below.
> 
> To explain my reasoning here: I am pretty much convinced at this point that we **need** a OK/NOK from the CI **now**, as this proved super useful for me when implementing the next TestGroup classes, to catch errors, and we need it given the size of the code base, as we reachitecture parts and bits of it. But this **only** works if the output is clean, if there are no errors reported. Otherwise, we won't bother checking the output, its too painful, and we won't know what was an error before, and what's new, because type errors can show up in any files anyway. That's why I want to reach "0 errors" ASAP, even if this means hiding some, and creating tickets to fix them.
> 
> Regarding these 4 files, these are older files, that have tons of typing errors. I probably fixed ~150 alone, but can't really spend more time addressing these, because I know these classes less, and I don't know if they are/will be useful after our merge.
> 
> So the best way to have the typecheck available for you/Noah/myself, is to ignore those ~50 remaining errors, to let us focus on what matters, and create tasks to either fix these issues (if the classes will be used) or drop the related code, if it won't be used.
> 
> I added the `make validate` (#194) as well, which ensures pyright and unit tests pass, which catches so many issues, but again, the output needs to be clean for that.

Oh yeah okay fair enough, that makes sense.

In that case, since we've already got an issue up for this let's go ahead and merge 👍🏼 

You're right, having type check on new PRs is way more important than getting to 100% on old stuff right now.

2021-01-28 11:12 UTC, mjftw approved these changes
Great to see so many fixed bugs in with these type checks!

2021-01-28 11:12 UTC, merged