Feature/session plan integration
Witekio/pluma-automation pull request #198
Opened 2021-02-01 22:05 UTC by Pixep

2021-02-02 17:24 UTC, prototypicalpro approved these changes
Looks good 👍.

2021-02-02 17:24 UTC, prototypicalpro commented on tests/generic/test/test_GroupedTest.py
> +# def test_GroupedTest_run(mock_board):
Maybe add a FIXME comment with why the test is failing?

2021-02-02 19:50 UTC, Pixep commented on tests/generic/test/test_GroupedTest.py
> +# def test_GroupedTest_run(mock_board):
That was just temporary, all good now.

2021-02-03 12:29 UTC, mjftw commented on pluma/test/testrunner.py
> +        body = f'''
You can do that?! Awesome!

2021-02-03 12:33 UTC, mjftw commented on pluma/test/testrunner.py
> +            log.log(test_message.ljust(column_limit) + '  ', level=LogLevel.IMPORTANT,
AFAIK `str.ljust()` doesn't truncate, only pad.

2021-02-03 12:37 UTC, mjftw commented on pluma/test/testrunner.py
> +            if test_success:
Not super important, but any way to reduce this nesting? Nested `if` statements like this are a bit meh

2021-02-03 12:38 UTC, mjftw commented on pluma/test/testrunner.py
> +                log.log(test_message.ljust(column_limit) + '  ', level=LogLevel.IMPORTANT,
Same comment as before, does this definitely truncate?

2021-02-03 12:45 UTC, mjftw requested changes
Another great PR 👍🏼 
Couple of comments, but nothing big.

2021-02-03 18:25 UTC, Pixep commented on pluma/test/testrunner.py
> +            if test_success:
Not really, because this is the logic to handle running the body, subtests, rest, depending if the previous steps worked or not, but not always. I merged two `if` below together however, because they were useless.

2021-02-03 18:26 UTC, Pixep commented on pluma/test/testrunner.py
> +            log.log(test_message.ljust(column_limit) + '  ', level=LogLevel.IMPORTANT,
Moved to a dedicated function

2021-02-03 18:26 UTC, Pixep commented on pluma/test/testrunner.py
> +                log.log(test_message.ljust(column_limit) + '  ', level=LogLevel.IMPORTANT,
Yes it was (text already truncated), but moved to a dedicated function

2021-02-05 10:24 UTC, mjftw approved these changes
Looks great, merge away

2021-02-05 10:24 UTC, merged