ConsoleBase.send_and_expect: fix output/match return
Witekio/pluma-automation pull request #48
Opened 2020-09-17 04:11 UTC by Pixep

Output now includes the full output received until the match, and the
match is the matched text, as the original 'send' method.
Expanded unit tests

2020-09-17 07:47 UTC, mjftw commented
Would you like me to review?

2020-09-22 08:35 UTC, mjftw requested changes
The code all looks great.
I like wrapping SerialConsoleProxy into a proper class, gives more flexibility.

The only concern I have is that this PR seems to be disabling running the tests in docker.
Is this really required?

2020-09-22 18:14 UTC, Pixep commented on .github/workflows/docker-image.yml
> +    # - name: Run tests from Docker
Yeah this is only disabling it for now, these are not stable, and keep failing randomly, so really no value for now, just noise.

2020-09-22 20:54 UTC, mjftw approved these changes

2020-09-22 20:54 UTC, merged