Feature/command runner any and all matches
Witekio/pluma-automation pull request #59
Opened 2020-09-19 18:57 UTC by Pixep

2020-09-23 10:00 UTC, mjftw requested changes
All looks good apart from I think one bug spotted.

2020-09-24 17:11 UTC, Pixep commented on pluma/test/shelltest.py
> +                 should_match_regex: list = None,  should_not_match_regex: list = None,
Thanks, I think I screwed that up with a rebase a some point

2020-09-25 08:19 UTC, mjftw commented
Looks like we need to tweak the Codacy rules because I'm totally fine with both those "errors".
I had to do quite a bit of modification to the rules on my personal repos to make them reflect the actual coding style I was after.

2020-09-25 08:25 UTC, mjftw approved these changes

2020-09-25 08:25 UTC, merged