Feature/add responds to ping test
Witekio/pluma-automation pull request #61
Opened 2020-09-19 19:36 UTC by Pixep

2020-09-22 09:28 UTC, mjftw requested changes
Code all looks good, just unsure about disabling the docker tests.

2020-09-22 09:28 UTC, mjftw commented on .github/workflows/docker-image.yml
> +    # - name: Run tests from Docker
Do we definitely need to disable running the tests in Docker?

2020-09-23 03:32 UTC, Pixep commented on .github/workflows/docker-image.yml
> +    # - name: Run tests from Docker
These are unstable on the CI, and already on master once rebase :). This is something we will have to investigate

2020-09-23 03:34 UTC, Pixep commented on .github/workflows/docker-image.yml
> +    # - name: Run tests from Docker
https://github.com/Witekio/pluma-automation/issues/69

2020-09-23 03:35 UTC, Pixep commented
Branch content approved, merging ahead of tomorrow's presentation

2020-09-23 03:35 UTC, merged