Feature/error no match include exclude
Witekio/pluma-automation pull request #63
Opened 2020-09-19 23:17 UTC by Pixep

2020-09-22 10:51 UTC, mjftw requested changes
The code looks good. Got a pointer on a minor improvement that could be made.

Only reason I've not approved is I'm not sure about disabling running the tests in the docker container.
Common theme I know.

2020-09-22 10:51 UTC, mjftw commented on pluma/cli/pythontestsprovider.py
> +        not_matched = match_strings
Not a PR requirement or anything, just a tip. I like this functional style, but you may think that this is actually worse.

This could be refactored to follow more functional programming style for less code:
```python
not_matched = [match for test in all_tests for match in match_strings if not PythonTestsProvider.test_match(test.name, match)]
```

Or using [itertools.product](https://docs.python.org/2/library/itertools.html#itertools.product):
```python
not_matched = [match for test, match in product(all_tests, match_strings) if not PythonTestsProvider.test_match(test.name, match)]
```

You can also do it using `filter` and  `map`, but that's probably less readable.

2020-09-22 10:51 UTC, mjftw commented on pluma/cli/pythontestsprovider.py
> +        not_matched = match_strings
This is a real aside, but from Python 3.8 we'd be able to do this all in 2 lines thanks to [Assignment Expressions](https://www.python.org/dev/peps/pep-0572/)  :)

```python
merlin@pangolin$ docker run -it python:3.8
Python 3.8.5 (default, Sep 10 2020, 16:47:10) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> if missing := [a for a in [1, 2, 3, 4, 5] if a > 3]:
...     print(missing)
...
[4, 5]
>>>

2020-09-23 03:39 UTC, Pixep commented on pluma/cli/pythontestsprovider.py
>                  return False
This is no test failure actually, this is selected or not tests from the test suite to be used in the step. All tests are listed with the `pluma tests` command, and selected/unselected with `include` and `exclude`.

2020-09-23 03:43 UTC, Pixep commented on pluma/cli/pythontestsprovider.py
> +        test_name_list = test_name.split('.')
Hmm this would be just the `find_python_tests` method, but I'm unsure how you want to put these together? They are indeed coupled, but also part of the same class. Or I missed the point?

2020-09-23 03:45 UTC, Pixep commented on pluma/cli/pythontestsprovider.py
> +        for i in range(min(len(test_name_list),
Oh interesting, I like it.

2020-09-23 03:55 UTC, Pixep commented on pluma/cli/pythontestsprovider.py
> +        not_matched = match_strings
Pretty cool to know. I personally couldn't maintain the functional version without thinking very hard for a good number of minutes, so for me personally, maintenance-wise, it is a bit worse at least _now_ :smile:. And I can imagine it to be the same for any new contributor. But that said its cool.

2020-09-23 04:00 UTC, Pixep commented
> Only reason I've not approved is I'm not sure about disabling running the tests in the docker container. Common theme I know.
Addressed code improvement comment, and merged ahead of tomorrow's presentation

2020-09-23 04:00 UTC, merged