Feature/uhubctl power control
Witekio/pluma-automation pull request #64
Opened 2020-09-20 01:04 UTC by Pixep

Add power control via uhubctl utility for USB hubs

2020-09-22 11:21 UTC, mjftw approved these changes
I've never used uhubctl before, looks pretty cool!

Since we're adding a new power controller, it would be good to add some reference to this in the docs (maybe in supported hardware).

2020-09-22 11:21 UTC, mjftw commented on pluma/core/power/uhubctl.py
> +            raise Exception('Uhubctl: "location" and/or "port" '
Would be better to raise a PDUError here.
https://github.com/Witekio/pluma-automation/blob/3265febdf77a33cc74f92eb888138040cc24b4dc/pluma/core/pdu.py#L11

Now that I look at it, maybe these should be called `PowerError` instead, nobody knows that `PDU` stands for Power Distribution Unit. Something to be put on another issue maybe.

2020-09-22 11:21 UTC, mjftw requested changes
Sorry meant to stick it as request changes for the Exception thing

2020-09-22 11:29 UTC, mjftw commented on pluma/core/power/uhubctl.py
> +            raise Exception('Uhubctl: "location" and/or "port" '
https://github.com/Witekio/pluma-automation/blob/master/docs/style-guide.md#exceptions

2020-09-23 04:03 UTC, Pixep commented on pluma/core/power/uhubctl.py
> +            raise Exception('Uhubctl: "location" and/or "port" '
Good point. Changed to `PDUError`

2020-09-23 04:07 UTC, Pixep commented
> Since we're adding a new power controller, it would be good to add some reference to this in the docs (maybe in supported hardware).

Added to the list!

2020-09-23 11:10 UTC, mjftw approved these changes

2020-09-23 11:10 UTC, merged