Add variables definition and subtitution support
Witekio/pluma-automation pull request #68
Opened 2020-09-20 22:39 UTC by Pixep

Variables can be defined in the target file, and will be substitued in
the tests file only.

2020-09-22 14:58 UTC, mjftw requested changes
Looks good.
Only minor comments. Quick fix then this is good to go.

2020-09-22 14:58 UTC, mjftw commented on tests/generic/cli/test_ConfigPreprocessor.py
> +    origina_content = 'content: value\notherline\nan a new one.'
Typo: ~~origina_content~~ original_content

2020-09-22 14:58 UTC, mjftw commented on pluma/cli/configpreprocessor.py
> +        vars_found = map(token_to_variable, vars_found)
I'd probably just put this one one line rather than redefining vars_found:
```python
vars_set = set(map(token_to_variable, vars_found))
```

And maybe rename it to something like `unique_vars` as I'm guessing that's what the set is being used for.

2020-09-22 14:58 UTC, mjftw commented on pluma/cli/configpreprocessor.py
> +            # remove '${' and '}'
Doesn't really matter as this is a nested function, but would be more typical to put this as a `'''` docstring rather than a `#` comment.

2020-09-22 14:58 UTC, mjftw commented on pluma/cli/config.py
> +class ConfigPreprocessor(ABC):
Using `ABC` here over `metaclass=ABCMeta` is inconsistent with the rest of the code.

But actually I think it's more readable and therefore better since it does the same.
The right thing to do is probably to swap the rest of the code over.

2020-09-23 04:12 UTC, Pixep commented on tests/generic/cli/test_ConfigPreprocessor.py
> +    origina_content = 'content: value\notherline\nan a new one.'
Done

2020-09-23 04:13 UTC, Pixep commented on pluma/cli/configpreprocessor.py
> +        vars_found = map(token_to_variable, vars_found)
Yep, makes sense. Done.

2020-09-23 04:14 UTC, Pixep commented on pluma/cli/configpreprocessor.py
> +            # remove '${' and '}'
Sure why not :)

2020-09-23 04:16 UTC, Pixep commented on pluma/cli/config.py
> +class ConfigPreprocessor(ABC):
Ok, this is consistent but only in `cli` yeah. Will create an issue, as both seem slightly different, and I prefer no to cause regressions here.

2020-09-23 04:18 UTC, Pixep commented on pluma/cli/config.py
> +class ConfigPreprocessor(ABC):
https://github.com/Witekio/pluma-automation/issues/70

2020-09-23 11:11 UTC, mjftw approved these changes

2020-09-23 11:12 UTC, mjftw commented
All good from my point of view!
Feel free to merge once the conflict is resolved.

2020-09-23 17:18 UTC, merged