pluma: substitue variables from environment
Witekio/pluma-automation pull request #82
Opened 2020-09-24 21:19 UTC by Pixep

Substitute variables defined as ${} in both configuration files. Closes 
Fixes #17

2020-09-25 08:47 UTC, mjftw requested changes
The code all looks good to me, only comments are more about behaviour.

2020-09-25 08:47 UTC, mjftw commented on README.md
> +  * Environment variables always take precedence over target definition variables, and can be used in both the target, and test configuration files. These are typically set with `EXPORT my_var=value`
Feels to me like it make more sense for variables defined in target config to overwrite env, since the target conf ones are specific to that board, whereas the env vars are global and less specific.
That would be my expected behaviour as a user.
I think the env is more likely to have leftover variables that people have set and forgotten about that cause odd errors by overwriting the local ones the user has just set.

2020-09-25 08:47 UTC, mjftw commented on README.md
> +  * Environment variables always take precedence over target definition variables, and can be used in both the target, and test configuration files. These are typically set with `EXPORT my_var=value`
Might be good to put something in the verbose/debug output mentioning the substitutions made and where they sourced from. Or maybe just a warning message when the same env var is detected locally in target config and globally in env.
I can see this being a cause of frustration for users when their env isn't used without them knowing and the tests behave wrong.

2020-09-25 08:47 UTC, mjftw commented on tests/generic/cli/test_Pluma.py
> +config_folder = path.join(path.dirname(__file__), 'test-configs/')
Might be good for us to put this somewhere accessible by multiple test files as I can see this being needed in a few of them. Doing so would enforce consistency throughout the test files.
Maybe passed in as a fixture? `configs_dir`?
Also, this doesn't matter so much but I prefer `dir` or `directory` over `folder` as it's more commonly used in Linux and it's primarily a Linux tool. But just personal preference.

2020-09-25 08:47 UTC, mjftw commented on tests/generic/cli/test_Pluma.py
> +def config_file_path(config: str):
Could be a fixture that returns this function, with the config folder wrapped into it in `conftest.py`

2020-09-25 08:47 UTC, mjftw commented on tests/generic/cli/test_Pluma.py
>  def run_all(test_file: str, target_file: str):
Nothing to stop this being a fixture which takes the previous fixture as a dependency. Not sure about this though. Thoughts?

2020-09-25 15:46 UTC, Pixep commented on README.md
> +  * Environment variables always take precedence over target definition variables, and can be used in both the target, and test configuration files. These are typically set with `EXPORT my_var=value`
So in the solutions I know (like AWS) env vars do override file config, because environment variables are more versatile than files. Hence you have Env vars > Local config > global config > default parameters. In GitLab for instance, you can use the same repo and files, but run the same builds with different environment variables. So you need environment variables to have a higher priority. Not sure about Yocto? Do have other examples? And yeah can add something to the --verbose mode to print vars.

2020-09-25 15:49 UTC, Pixep commented on tests/generic/cli/test_Pluma.py
>  def run_all(test_file: str, target_file: str):
Yeah it does work. Added here: https://github.com/Witekio/pluma-automation/issues/95

2020-09-25 15:51 UTC, mjftw commented on README.md
> +  * Environment variables always take precedence over target definition variables, and can be used in both the target, and test configuration files. These are typically set with `EXPORT my_var=value`
Oh yeah fair enough, if that's the done thing then let's do that.
A warning about redefined variables would still be nice though.

2020-09-26 23:28 UTC, Pixep commented on tests/generic/cli/test_Pluma.py
> +def config_file_path(config: str):
Added here: #95

2020-09-26 23:28 UTC, Pixep commented on tests/generic/cli/test_Pluma.py
> +config_folder = path.join(path.dirname(__file__), 'test-configs/')
Added here: #95

2020-09-28 10:06 UTC, mjftw approved these changes

2020-09-28 10:06 UTC, merged