pluma.test: split test.py in different files
Witekio/pluma-automation pull request #85
Opened 2020-09-25 01:19 UTC by Pixep

`test.py` was way to big, step toward simplifying the whole architecture

2020-09-25 09:32 UTC, mjftw commented
> `test.py` was way to big, step toward simplifying the whole architecture

Completely agree, all of the test framework files and classes are way too heavy.
I've wanted to split them apart for ages so thanks for this!

2020-09-25 09:58 UTC, mjftw requested changes

2020-09-25 09:58 UTC, mjftw commented on pluma/test/__init__.py
> +    AbortTestingAndReport  # noqa: F401
What are all these `# noqa: F401` lines about?

2020-09-25 09:58 UTC, mjftw commented on pluma/test/testrunner.py
> +    """Orchestrates tests globally"""
Might be worth mentioning that It only orchestrates a set of tests to run a single time.
Only half the picture with `TestController`.

2020-09-27 00:45 UTC, Pixep commented on pluma/test/__init__.py
> +    AbortTestingAndReport  # noqa: F401
Yep, ignored it in Codacy

2020-09-27 00:45 UTC, Pixep commented on pluma/test/testrunner.py
> +    """Orchestrates tests globally"""
Updated

2020-09-28 10:24 UTC, mjftw approved these changes
Looks great 👍🏼

2020-09-28 10:25 UTC, merged